### ISSUE TITLE
Travel India Navbar not working saar

### ISSUE THREAD

**Issue by KaustubhRai** [zpratikpathak/25-Javascript-Projects-for-beginner#1]
when clicked on any links on the navbar, nothing works. the slideshow is the only thing that works lol 

nothing works saar, opening issues saar, open source contribution, foss saar. 

https://github.com/zpratikpathak/25-Javascript-Projects-for-beginner/assets/28558847/1908787e-44f6-43ff-bdf1-2137294a238f

**Comment by zpratikpathak** [comment]
it,s a single pagge script, navbar is only for demo, you can create more page and link to navbar
